### ISSUE TITLE
MorrisExperimentGrid hangs

### ISSUE THREAD

**Issue by jschueller** [openturns/otmorris#32]
Seems the while loop hangs when there are not enough trajectories under certain conditions (dim=1, levels=[5], n_traj=10):

```
from __future__ import print_function
import openturns as ot
import otmorris

# Use Case 1 : define a k-grid level (so delta = 1/(k-1))
r = 10
morris_experiment = otmorris.MorrisExperimentGrid([5], r)
X = morris_experiment.generate()
print("Morris experiment generated from grid = ", X)
```

Here we enforce unique trajectories.
solution: compute the number of possible trajectories: (d-1)^d modulo the jumpstep wrt out of bound.

**Comment by sofianehaddad** [comment]
Other solution : relax uniqueness constraint and warn if we get duplicates
I am not sure about " (d-1)^d modulo the jumpstep"

**Comment by jschueller** [comment]
@sofianehaddad the KPermutationsDistribution defining the permutations is not used, it that ok ?
https://github.com/openturns/otmorris/blob/master/lib/src/MorrisExperimentGrid.cxx#L112

**Comment by sofianehaddad** [comment]
@jschueller https://github.com/openturns/otmorris/blob/master/lib/src/MorrisExperimentGrid.cxx#L141

**Comment by jschueller** [comment]
@sofianehaddad, yes but that realization is not used

**Comment by sofianehaddad** [comment]
indeed...

**Comment by jschueller** [comment]
is there a step missing ?

**Comment by sofianehaddad** [comment]
It seems. I will have a look asap

**Comment by sofianehaddad** [comment]
Probably

**Comment by sofianehaddad** [comment]
@jschueller I am back on it
What should we do if number of trajectories is greater than the full number of possibilities ? Warn and replace `N` or throw an exception ?

**Comment by jschueller** [comment]
I think its best to just throw than replacing N with a warning that can be missed
