### ISSUE TITLE
Module handle only uniform distributions

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/otmorris#39]
The module handle only uniform inputs.
If input model contains non-uniform distributions, there is not any framework to handle them

**Comment by jschueller** [comment]
I think we discussed this already with Antoine, maybe using iso-transfos would bias the results, a limitation of the method ?

**Comment by sofianehaddad** [comment]
Maybe. Any workaround ?

**Comment by mbaudin47** [comment]
I think that there is no way to make it work in another setting as the uniform independent marginals. This is an intrinsic property of the method. Perhaps using a Distribution was not a correct idea: an `Interval` would better fit.
