### ISSUE TITLE
MorrisExperimentLHS segfaults

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/otmorris#40]
The following script segfaults with `otmorris` 0.7 on `OS X` installed via `conda`:

```
import openturns as ot
import otmorris
X = ot.LHSExperiment(ot.ComposedDistribution([ot.Uniform(0,1)]*4), 50, False, False).generate()
morris_experiment = otmorris.MorrisExperimentLHS(X, 10)
morris_experiment.generate()
```
The same code using cd0423c33751b8745c43f2c346fdaf6712e5b706 has no issue on `OS X` (compiled on by laptop).

It seems that bug is `conda` related?

**Comment by sofianehaddad** [comment]
The code seems to work "normally" with current `master` on `linux`. 
I will try to check `master` on `OS X`

**Comment by jschueller** [comment]
I think this may have to do with the api change between 1.14rc1 and 1.14, it should be fixed now
