### ISSUE TITLE
Installation on Google colab

### ISSUE THREAD

**Issue by mbaudin47** [openturns/otmorris#44]
Some users want to use otmorris from Google colab:

https://colab.research.google.com

But colab does not know about conda. Is there any way to get around this?

**Comment by sofianehaddad** [comment]
You can! I already experimented this feature relying on `otconda`

For install:
```
!wget https://github.com/openturns/otconda/releases/download/v1.16/otconda3-1.16-Linux-x86_64.sh && bash otconda3-1.16-Linux-x86_64.sh -bfp /usr/local
```
Then
```
import sys
sys.path.append('/usr/local/lib/python3.8/site-packages')
```

Finally
```
import openturns as ot
import otmorris 
```

You also might want to know more about your `conda` install. For example:
```
!conda info --all
```
or `!conda list` can be applied!

**Comment by sofianehaddad** [comment]
Notebook example : [using_otconda.ipynb.zip](https://github.com/openturns/otmorris/files/6006067/using_otconda.ipynb.zip)

**Comment by mbaudin47** [comment]
Thank you *very* much! I test this.
