### ISSUE TITLE
Bug on otmorris?

### ISSUE THREAD

**Issue by m-balesdent** [openturns/otmorris#57]
### What happened?

I think there is a bug on otmorris function `MorrisExperimentGrid` that has been introduced in the last release of otmorris.

On the last release of otmorris, the argument 'bounds' was removed from the method `otmorris.MorrisExperimentGrid`. Consequently, the morris_experiment is automatically generated on $[0,1]^d$.  

Then, it is not possible to directly use the black-box function on the samples provided by `otmorris.MorrisExperimentGrid`  to compute the responses of the function because the domain of definition of this function can be different than $[0,1]^d$.

### How to reproduce the issue?

```shell
import openturns as ot
import openturns.viewer as otv
import otmorris

# use the reference 20-d function from the Morris paper
f = ot.Function(otmorris.MorrisFunction())
dim = f.getInputDimension()

# Number of trajectories
r = 10

# Define experiments in [0,1]^20
# p-levels
p = 5
morris_experiment = otmorris.MorrisExperimentGrid([p] * dim, r)
bounds = ot.Interval(dim)  
X = morris_experiment.generate()
## What happen if the function `f` is not defined on [0,1]^d?
Y = f(X)
```

### Version

otmorris v 0.16

### Operating System

Windows

### Installation media

pip

**Comment by jschueller** [comment]
looks fine: http://openturns.github.io/otmorris/master/user_manual/_generated/otmorris.MorrisExperimentGrid.html#otmorris.MorrisExperimentGrid

**Comment by m-balesdent** [comment]
ok, my bad. I followed the order in the description of the parameters that is different than the order or argument in the signature of the function : 
![image](https://github.com/user-attachments/assets/641cdf9d-ea76-4f9f-8f49-5210d9a6f500)

**Comment by jschueller** [comment]
no pb

**Comment by jschueller** [comment]
maybe the interval should be the last argument
